### ISSUE TITLE
Appear in the Powered By Faust page ?

### ISSUE THREAD

**Issue by sletz** [chevremaudite/zosimos#2]
I discovered your zosimos  project on GitHub. Very promising !

Would you be interested to appear on the [Powered By Faust](https://faust.grame.fr/community/made-with-faust/) page ? This could help having people interested to contribute.

If yes, do you have any picture/screenshot I could use in the project presentation?

Thanks in advance.

**Comment by chevremaudite** [comment]
Hi Stéphane,
Thanks for your interest in my project, it is truly heartwarming to see people becoming interested in what I do. 
On the long term, I would be really glad to be part of the powered by FAUST page. 
I have found many really interesting projects through the page and as you said, it could help to bring visibility to zosimos. 

This being said, I think it is maybe a bit too early to appear on the page. 
As you may or may not know, zosimos is a long term project but I just started actually coding it, and for the moment it's nothing but a collection of very simple unfinished synth engines, not really interconnected or anything like that. 
As for the hardware part, I have plans but development just hasn't started yet.
I think maybe in a month or so I will have a first (software only) release, and I think that could be a good time to look for contributors; I will also be able to provide more resources to present the project. 

Thanks again for your proposal, but I think for the moment the project just isn't ready yet. If it's OK for you, I will gladly contact you back once it has reached a state where it can be better presented and understood by everyone.

**Comment by sletz** [comment]
OK, perfect for me.
